### ISSUE TITLE
Fails for Windows Installs outside User Directory

### ISSUE THREAD

**Issue by Lucaszw** [conda/constructor#148]
Conda constructor fails on Windows for Miniconda and Anaconda installs outside of the user directory. 
I've noticed this behavior on my local machine (when I have Miniconda installed on a separate hardrive from my system) and on Appveyor using their default Miniconda installs.

```
NSIS version: v3.01
Reading: A:\Miniconda2\lib\site-packages\constructor\nsis\main.nsi.tmpl
MSVC runtimes found: [u'vs2015_runtime-14.0.25420-0.tar.bz2']
Created c:\users\lucaszw\appdata\local\temp\tmpmngr0m\main.nsi file
Calling: ['A:\\Miniconda2\\NSIS\\makensis.exe', '/V2', 'c:\\users\\lucaszw\\appdata\\local\\temp\\tmpmngr0m\\main.nsi']
Usage: AddSize size_to_add_to_section_in_kb
Error in script "c:\users\lucaszw\appdata\local\temp\tmpmngr0m\main.nsi" on line 858 -- aborting creation process
Traceback (most recent call last):
  File "A:\Miniconda2\Scripts\constructor-script.py", line 5, in <module>
    sys.exit(constructor.main.main())
  File "A:\Miniconda2\lib\site-packages\constructor\main.py", line 221, in main
    dry_run=opts.dry_run)
  File "A:\Miniconda2\lib\site-packages\constructor\main.py", line 128, in main_build
    create(info, verbose=verbose)
  File "A:\Miniconda2\lib\site-packages\constructor\winexe.py", line 241, in create
    check_call(args)
  File "A:\Miniconda2\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['A:\\Miniconda2\\NSIS\\makensis.exe', '/V2', 'c:\\users\\lucaszw\\appdata\\local\\temp\\tmpmngr0m\\main.nsi']' returned non-zero exit status 1
```

**Comment by nehaljwani** [comment]
Which version of constructor are you using? This seems to be a duplicate of https://github.com/conda/constructor/issues/133 which was fixed in https://github.com/conda/constructor/commit/9b9491ea490c3a1e2fe232fd6454b5e342f86616

**Comment by nehaljwani** [comment]
Try updating constructor to v2.0.1?

**Comment by Lucaszw** [comment]
Yes that did the trick (I was using v2.0.0 from conda-forge)
