### ISSUE TITLE
How to specify pip dependencies in construct.yml?

### ISSUE THREAD

**Issue by rossant** [conda/constructor#15]
Using the following syntax (like in `environment.yml`):

```
  - pip:
      - somepackage
```

results in:

```
platform: linux-64
Traceback (most recent call last):
  File "/home/cyrille/miniconda3/bin/constructor", line 6, in <module>
    sys.exit(main())
  File "/home/cyrille/miniconda3/lib/python3.5/site-packages/constructor/main.py", line 145, in main
    verbose=opts.verbose)
  File "/home/cyrille/miniconda3/lib/python3.5/site-packages/constructor/main.py", line 78, in main_build
    info[key] = [line.strip() for line in info[key]]
  File "/home/cyrille/miniconda3/lib/python3.5/site-packages/constructor/main.py", line 78, in <listcomp>
    info[key] = [line.strip() for line in info[key]]
AttributeError: 'dict' object has no attribute 'strip'
```

**Comment by ilanschnell** [comment]
Constructor only supports the bundling of conda packages.  Sorry.

**Comment by willingc** [comment]
@ilanschnell If the pip dependencies were bundled as a conda package on a user's channel, constructor could add them. Correct?

**Comment by bkreider** [comment]
Yes.  If you turned them into conda packages it would work.

**Comment by willingc** [comment]
Thanks for confirming @bkreider
