### ISSUE TITLE
Conda 4.3.31: `constructor --test` results in `ImportError: The _imagingft C module is not installed`

### ISSUE THREAD

**Issue by cfobel** [conda/constructor#153]
# Setup

 1. Install [`Miniconda2-4.3.31-Windows-x86.exe`][miniconda]
 2. Install `constructor` (explicitly install `conda==4.3.31` to prevent `conda` from upgrading automatically):

        conda install constructor conda==4.3.31
 3. Run `constructor` tests:

        constructor --test

Here is the test environment: [env-python-2.7.14-conda-4.3.31.yaml.zip](https://github.com/conda/constructor/files/1602450/env-python-2.7.14-conda-4.3.31.yaml.zip)

# Expected behaviour

Output similar to:

```
sys.prefix: C:\Users\chris\Miniconda2
sys.version: 2.7.14 | packaged by conda-forge | (defa ...
constructor version: 2.0.1
conda interface type: conda
conda interface version: 4.4.6
location: C:\Users\chris\Miniconda2\lib\site-packages\constructor
pillow version: 3.0.0
Checking for 'C:\Users\chris\Miniconda2\NSIS\makensis.exe'
NSIS version: v3.01
Reading: C:\Users\chris\Miniconda2\lib\site-packages\constructor\nsis\main.nsi.tmpl
.................
----------------------------------------------------------------------
Ran 17 tests in 0.003s

OK
```

# Observed behaviour

An `ImportError` is raised:

```
sys.prefix: C:\Users\chris\Miniconda2.7.14-x86
sys.version: 2.7.14 |Anaconda, Inc.| (default, Nov  8 ...
constructor version: 2.0.1
conda interface type: conda
conda interface version: 4.3.31
location: C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor
pillow version: 4.3.0
Checking for 'C:\Users\chris\Miniconda2.7.14-x86\NSIS\makensis.exe'
NSIS version: v3.01
Reading: C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\nsis\main.nsi.tmpl
Traceback (most recent call last):
  File "C:\Users\chris\Miniconda2.7.14-x86\Scripts\constructor-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\main.py", line 205, in main
    tests_main()
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\tests\__init__.py", line 34, in main
    test_write_images()
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\tests\test_imaging.py", line 15, in test_write_images
    write_images(info, tmp_dir)
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\imaging.py", line 96, in write_images
    im = f(info)
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\imaging.py", line 46, in mk_welcome_image
    font = ImageFont.truetype(ttf_path, 20)
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\PIL\ImageFont.py", line 259, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\PIL\ImageFont.py", line 135, in __init__
    if core.HAVE_RAQM:
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\PIL\ImageFont.py", line 37, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```

**Note: a _different_ import error occurs with `conda==4.4.6`.  See #152 for details.**

[miniconda]: https://repo.continuum.io/miniconda/Miniconda2-4.3.31-Windows-x86.exe

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
