### ISSUE TITLE
conda 4.5.0rc0 breaks constructor

### ISSUE THREAD

**Issue by nehaljwani** [conda/constructor#176]
```
Traceback (most recent call last):
  File "/home/nwani/conda_inst/bin/constructor", line 11, in <module>
    load_entry_point('constructor==2.0.2', 'console_scripts', 'constructor')()
  File "/home/nwani/conda_inst/lib/python3.6/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/home/nwani/conda_inst/lib/python3.6/site-packages/constructor/main.py", line 128, in main_build
    create(info, verbose=verbose)
  File "/home/nwani/conda_inst/lib/python3.6/site-packages/constructor/shar.py", line 80, in create
    preconda_write_files(info, tmp_dir)
  File "/home/nwani/conda_inst/lib/python3.6/site-packages/constructor/preconda.py", line 129, in write_files
    write_index_cache(info, dst_dir)
  File "/home/nwani/conda_inst/lib/python3.6/site-packages/constructor/preconda.py", line 37, in write_index_cache
    write_repodata(cache_dir, url)
  File "/home/nwani/conda_inst/lib/python3.6/site-packages/constructor/conda_interface.py", line 39, in write_repodata
    from conda.core.repodata import fetch_repodata_remote_request
ModuleNotFoundError: No module named 'conda.core.repodata'
```

**Comment by nehaljwani** [comment]
cc @kalefranz
