### ISSUE TITLE
Issue in Constructor 2.2.2

### ISSUE THREAD

**Issue by elijahomolo** [conda/constructor#226]
Constructor is throwing the following error:

```
Checking for duplicate files ...


Traceback (most recent call last):

File "C:\Users\toby\miniconda3-64\Scripts\constructor-script.py", line 10, in <module>
sys.exit(main())
File "C:\Users\toby\miniconda3-64\lib\site-packages\constructor\main.py", line 221, in main
dry_run=opts.dry_run)
File "C:\Users\toby\miniconda3-64\lib\site-packages\constructor\main.py", line 113, in main_build
fcp_main(info, verbose=verbose, dry_run=dry_run)
File "C:\Users\toby\miniconda3-64\lib\site-packages\constructor\fcp.py", line 237, in main
ignore_duplicate_files, verbose, dry_run
File "C:\Users\toby\miniconda3-64\lib\site-packages\constructor\fcp.py", line 207, in _main
pc_recs, platform, ignore_duplicate_files
File "C:\Users\toby\miniconda3-64\lib\site-packages\constructor\fcp.py", line 120, in check_duplicates_files
size = path_data.size_in_bytes or getsize(join(extracted_package_dir, short_path))
AttributeError: 'PathData' object has no attribute 'size_in_bytes'

```

Downgrading to version 2.1.1 fixes the issue. Modifying miniconda3-64\lib\site-packages\constructor\fcp.py line 120 by removing the path_data.size_in_bytes call and leaving the 'size' variable just as getsize(join(extracted_package_dir, short_path)) also worked as a workaround.

**Comment by nehaljwani** [comment]
Which version of conda is present in the environment where you are trying to run constructor?

**Comment by H0R5E** [comment]
I can confirm this. I've attached the patch I used to fix it with a try-except block, as the "or" statement didn't work when the size_in_bytes attribute was missing from the PathData variant.

```
>conda info

     active environment : base
    active env location : C:\Anaconda\envs\_constructor
            shell level : 1
       user config file : C:\Users\Work\.condarc
 populated config files : C:\Users\Work\.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : C:\Anaconda\envs\_constructor  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/dataonlygreater/win-64
                          https://conda.anaconda.org/dataonlygreater/noarch
                          https://conda.anaconda.org/t/<TOKEN>/topper/win-64
                          https://conda.anaconda.org/t/<TOKEN>/topper/noarch
          package cache : C:\Anaconda\envs\_constructor\pkgs
                          C:\Users\Work\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda\envs\_constructor\envs
                          C:\Users\Work\AppData\Local\conda\conda\envs
                          C:\Users\Work\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/2.7.15 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```

```
>conda list
# packages in environment at C:\Anaconda\envs\_constructor:
#
# Name                    Version                   Build  Channel
...
conda                     4.5.11                   py27_0
conda-env                 2.6.0                         1
constructor               2.2.0                     <pip>
...
```

[patch.diff.txt](https://github.com/conda/constructor/files/2544819/patch.diff.txt)

**Comment by nehaljwani** [comment]
Thanks for the patch @H0R5E . This appears to affect those packages which were built with an old version of conda-build.

**Comment by H0R5E** [comment]
Hi @nehaljwani, I actually think my solution was not complete. I'm guessing there is a case where the size_in_bytes method returns a value which casts to False, hence the original "or" statement.

In PR #233 I've replaced the original command in the try block.
