### ISSUE TITLE
Couldn't construct any local packages anymore

### ISSUE THREAD

**Issue by huamichaelchen** [conda/constructor#248]
Hi conda/constructor team, 

This is confusing, because our `constructor` builds failed even though we haven't changed anything on anything conda related. 

As you can see from the error below, I turned on `--debug` mode as well and specifically to point to the `*.bz2` file I want to "construct" in the `construct.yaml` file as well. 

<details><summary>Here is the error</summary>

```
Building installer:  dist/installer/kyber-evaluation-0.3.3+13.gdb87a3d.dirty-linux-64.sh
platform: linux-64
DEBUG:conda.core.solve:solving prefix /constructor/no-environment
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec("python"), MatchSpec("dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0"), MatchSpec("entrypoints")})
  prune: False
Collecting package metadata: - DEBUG:conda.core.package_cache_data:package cache directory '/home/host-user/.conda/constructor/linux-64' writable: True
DEBUG:conda.core.subdir_data:Local cache timed out for file:///work/dist/conda/linux-64 at /home/host-user/.conda/constructor/linux-64/cache/17fcc4e2.json
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
INFO:conda._vendor.auxlib.logz:request is 'None' for Response object with url file:///work/dist/conda/linux-64/repodata.json
DEBUG:conda.core.subdir_data:
<<FILE 200 None
< Content-Type: application/json
< Last-Modified: Fri, 22 Mar 2019 22:18:44 GMT
< Content-Length: 2742
< Elapsed: 00:00.001817

{ 'info': {'subdir': 'linux-64'},
  'packages': { 'kyber-evaluation-0.3.3+13.gdb87a3d.dirty-py37_0.tar.bz2': { 'build': 'py37_0',
                                                                             'build_number': 0,
                              


DEBUG:conda.core.subdir_data:Saving pickled state for file:///work/dist/conda/linux-64 at /home/host-user/.conda/constructor/linux-64/cache/17fcc4e2.json
DEBUG:conda.core.subdir_data:Local cache timed out for file://work/dist/conda/noarch at /home/host-user/.conda/constructor/linux-64/cache/c489b8b9.json
INFO:conda._vendor.auxlib.logz:request is 'None' for Response object with url file://work/dist/conda/noarch/repodata.json
DEBUG:conda.core.subdir_data:
<<FILE 200 None
< Content-Type: application/json
< Last-Modified: Fri, 22 Mar 2019 20:53:09 GMT
< Content-Length: 103
< Elapsed: 00:00.000064

{ 'info': {'subdir': 'noarch'},
  'packages': {},
  'removed': [],
  'repodata_version': 1}


DEBUG:conda.core.subdir_data:Saving pickled state for file://work/dist/conda/noarch at /home/host-user/.conda/constructor/linux-64/cache/c489b8b9.json
DEBUG:conda.core.subdir_data:Local cache timed out for file:///work/dist/conda/noarch at /home/host-user/.conda/constructor/linux-64/cache/316e49be.json
INFO:conda._vendor.auxlib.logz:request is 'None' for Response object with url file:///work/dist/conda/noarch/repodata.json
DEBUG:conda.core.subdir_data:
<<FILE 200 None
< Content-Type: application/json
< Last-Modified: Fri, 22 Mar 2019 20:53:09 GMT
< Content-Length: 103
< Elapsed: 00:00.000065

{ 'info': {'subdir': 'noarch'},
  'packages': {},
  'removed': [],
  'repodata_version': 1}


DEBUG:conda.core.subdir_data:Saving pickled state for file:///work/dist/conda/noarch at /home/host-user/.conda/constructor/linux-64/cache/316e49be.json
DEBUG:conda.core.subdir_data:Using cached repodata for https://conda.anaconda.org/conda-forge/noarch at /home/host-user/.conda/constructor/linux-64/cache/09cdf8bf.json. Timeout in 737 sec
DEBUG:conda.core.subdir_data:found pickle file /home/host-user/.conda/constructor/linux-64/cache/09cdf8bf.q
DEBUG:conda.core.subdir_data:Using cached repodata for https://conda.anaconda.org/conda-forge/linux-64 at /home/host-user/.conda/constructor/linux-64/cache/497deca9.json. Timeout in 703 sec
DEBUG:conda.core.subdir_data:found pickle file /home/host-user/.conda/constructor/linux-64/cache/497deca9.q
- DEBUG:conda.core.subdir_data:Local cache timed out for file://work/dist/conda/linux-64 at /home/host-user/.conda/constructor/linux-64/cache/efb979f4.json
INFO:conda._vendor.auxlib.logz:request is 'None' for Response object with url file://work/dist/conda/linux-64/repodata.json
DEBUG:conda.core.subdir_data:
<<FILE 200 None
< Content-Type: application/json
< Last-Modified: Fri, 22 Mar 2019 22:18:44 GMT
< Content-Length: 2742
< Elapsed: 00:00.000079

{ 'info': {'subdir': 'linux-64'},
  'packages': { 'kyber-evaluation-0.3.3+13.gdb87a3d.dirty-py37_0.tar.bz2': { 'build': 'py37_0',
                                                                             'build_number': 0,
                              


DEBUG:conda.core.subdir_data:Saving pickled state for file://work/dist/conda/linux-64 at /home/host-user/.conda/constructor/linux-64/cache/efb979f4.json
done
Solving environment: \ DEBUG:conda.resolve:Checking if the current environment is consistent
DEBUG:conda.core.solve:inconsistent precs: None
DEBUG:conda.resolve:Retrieving packages for: 
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0
  - entrypoints
  - python
failed
Traceback (most recent call last):
  File "/opt/conda/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/opt/conda/lib/python3.7/site-packages/constructor/main.py", line 113, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/opt/conda/lib/python3.7/site-packages/constructor/fcp.py", line 241, in main
    ignore_duplicate_files, verbose, dry_run
  File "/opt/conda/lib/python3.7/site-packages/constructor/fcp.py", line 182, in _main
    precs = list(solver.solve_final_state())
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 465, in _run_sat
    conflicting_specs = ssc.r.get_conflicting_specs(tuple(final_environment_specs))
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 852, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 356, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 244, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> grpcio -> c-ares[version='>=1.15.0,<2.0a0'] -> libgcc-ng[version='>=7.3.0']
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> grpcio -> libstdcxx-ng[version='>=7.3.0']
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> grpcio -> openssl[version='>=1.0.2p,<1.0.3a']
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> osi3
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> panda3d
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> pyyaml=5.1
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> sacred=0.7.4.f88
Makefile:149: recipe for target 'dist/installer/kyber-evaluation-0.3.3+13.gdb87a3d.dirty-linux-64.sh' failed

```
</details>

<details><summary>construct.yaml</summary>

```
name: kyber-evaluation
version: 0.3.3_13.gdb87a3d.dirty

channels:
  - https://conda.anaconda.org/conda-forge/
  - file:///work/dist/conda/


specs:
  - entrypoints
  #- kyber-evaluation
  - file://work/dist/conda/linux-64/kyber-evaluation-0.3.3+13.gdb87a3d.dirty-py37_0.tar.bz2

default_prefix: /opt/kyber-evaluation

post_install: post-install.sh

register_python_default: False
```
</summary>

<details><summary>conda list results</summary>

```bash
conda list
# packages in environment at /opt/conda/envs/kyber-evaluation:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
beautifulsoup4            4.7.1                 py37_1001    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
c-ares                    1.15.0            h14c3975_1001    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37hf0e25f4_1    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cryptography              2.6.1            py37h9d9f1b6_0    conda-forge
docker-py                 3.7.1                    py37_0    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
docopt                    0.6.2                    pypi_0    pypi
entrypoints               0.3                   py37_1000    conda-forge
flake8                    3.7.7                    py37_0    conda-forge
flake8-polyfill           1.0.2                      py_0    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
gitdb2                    2.0.5                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
grpcio                    1.16.1           py37hf8bcb03_1  
grpcio-tools              1.16.1           py37he6710b0_0  
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
jsonpickle                0.9.6                    pypi_0    pypi
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libprotobuf               3.7.0                h8b12597_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libxml2                   2.9.8             h143f9aa_1005    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
lxml                      4.3.2            py37h23eabaa_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
more-itertools            4.3.0                 py37_1000    conda-forge
munch                     2.3.2                    pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.2           py37h8b7e671_1    conda-forge
openblas                  0.3.5                ha44fe06_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
osi3                      3.1.2                    py37_0    local
packaging                 19.0                       py_0    conda-forge
panda3d                   1.10.2                   pypi_0    pypi
pandas                    0.24.2           py37hf484d3e_0    conda-forge
pep8-naming               0.8.2                      py_0    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pluggy                    0.9.0                      py_0    conda-forge
protobuf                  3.7.0            py37he1b5a44_1    conda-forge
psutil                    5.6.1            py37h14c3975_0    conda-forge
py                        1.8.0                      py_0    conda-forge
py-cpuinfo                5.0.0                    pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pydocstyle                3.0.0                    py37_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytest                    4.3.1                    py37_0    conda-forge
python                    3.7.2                h381d211_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    5.1                      pypi_0    pypi
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
sacred                    0.7.4                    pypi_0    pypi
setuptools                40.8.0                   py37_0    conda-forge
shapely                   1.6.4           py37h2afed24_1003    conda-forge
six                       1.12.0                py37_1000    conda-forge
smmap2                    2.0.5                      py_0    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
soupsieve                 1.8                      py37_0    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tabulate                  0.8.3                      py_0    conda-forge
tinydb                    3.13.0                     py_0    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
websocket-client          0.56.0                   py37_0    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
wrapt                     1.11.1                   pypi_0    pypi
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</summary>

**Comment by huamichaelchen** [comment]
On a related note, I'm a bit confused about the error message below. If it means that: 

grpcio requires c-ares > 1.15.0 and < 2.0a0, and of which depends on libgcc-ng needs to be > 7.3.0?

then my current environment (`conda list`) does have libgcc-ng 8.2.0, and c-ares 1.15.0. As matter of fact, what `conda constructor` complains about dependency error, I have all of them in my current activated conda environment. 

So is it that somehow at run time, `constructor` is looking in some other environment?

```bash
conda.exceptions.ResolvePackageNotFound: 
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> grpcio -> c-ares[version='>=1.15.0,<2.0a0'] -> libgcc-ng[version='>=7.3.0']
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> grpcio -> libstdcxx-ng[version='>=7.3.0']
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> grpcio -> openssl[version='>=1.0.2p,<1.0.3a']
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> osi3
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> panda3d
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> pyyaml=5.1
  - dist/conda/linux-64::kyber-evaluation==0.3.3+13.gdb87a3d.dirty=py37_0 -> sacred=0.7.4.f88

```

**Comment by huamichaelchen** [comment]
Alright, I think this is probably specific package issue, or perhaps I didn't use `constructor` incorrectly. 
However, it would've been really helpful if there are some better documentation out there about this. Not sure why, there are a lot of conda documentations are broken links... :cry:  For instance, https://docs.conda.io/projects/conda-build/en/latest/source/resources/variants.html

I'm assuming Anaconda is going through revamping of their products?
