### ISSUE TITLE
"packages" not supported anymore.

### ISSUE THREAD

**Issue by AXGKl** [conda/constructor#250]
1. constructor is amazing!!!

Smalish wtf, checking the grin example: 

```
(base) [root@axc2_master examples]# constructor grin/
platform: linux-64
Error: unknown key 'packages' in construct.yaml
(base) [root@axc2_master examples]# constructor --version
constructor version: 2.3.0
```

Checked git, this key seems to have been never in(?) 

When I comment it out it 

<details>
 <summary>crashes...</summary>
    
```
(base) [root@axc2_master grin]# git diff .
diff --git a/examples/grin/construct.yaml b/examples/grin/construct.yaml
index f08fc22..19dd70b 100644
--- a/examples/grin/construct.yaml
+++ b/examples/grin/construct.yaml
@@ -22,8 +22,8 @@ exclude:

 # explicitly listed packages
 # pkgs.txt
-packages:
-  - python-2.7.9-0.tar.bz2
+#packages:
+#  - python-2.7.9-0.tar.bz2

 #install_in_dependency_order: True

(base) [root@axc2_master grin]# constructor .
platform: linux-64
Traceback (most recent call last):
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 132, in env_vars
    callback(True)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 1110, in reset_context
    context.__init__(search_path, argparse_args)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 285, in __init__
    argparse_args=argparse_args)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/common/configuration.py", line 762, in __init__
    self._set_search_path(search_path)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/common/configuration.py", line 767, in _set_search_path
    self._search_path = IndexedSet(search_path)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/_vendor/boltons/setutils.py", line 96, in __init__
    self.update(other)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/_vendor/boltons/setutils.py", line 310, in update
    for o in other:
TypeError: 'bool' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/root/miniconda3/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/data/root/miniconda3/lib/python3.7/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/data/root/miniconda3/lib/python3.7/site-packages/constructor/main.py", line 113, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/data/root/miniconda3/lib/python3.7/site-packages/constructor/fcp.py", line 237, in main
    }, conda_reset_context):
  File "/data/root/miniconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 141, in env_vars
    callback(False)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 1110, in reset_context
    context.__init__(search_path, argparse_args)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 285, in __init__
    argparse_args=argparse_args)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/common/configuration.py", line 762, in __init__
    self._set_search_path(search_path)
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/common/configuration.py", line 768, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "/data/root/miniconda3/lib/python3.7/site-packages/conda/common/configuration.py", line 386, in load_file_configs
    expanded_paths = tuple(expand(path) for path in search_path)
TypeError: 'bool' object is not iterable
(base) [root@axc2_master grin]#
```

</details>

=> that example needs an update it contains most of your features for pre and post install...

Then: What is keep_pkgs supposed to do? Setting it to True still does only render me with repodata.json files but not e.g. the build specs.

Thanks again for this great tool - and no stress, I can workaround my probs... Will store the build specs elsewhere then, by "installing" them or so.

**Comment by nehaljwani** [comment]
Please try with conda >=4.5.x,<4.6.9

**Comment by AXGKl** [comment]
works thanks, closing.
