### ISSUE TITLE
Support installation of packages from full URLs

### ISSUE THREAD

**Issue by cab938** [conda/constructor#267]
Here is an MWE construct.yaml

```
name: a
version: 0.1

install_in_dependency_order: True

channels:
  - https://repo.anaconda.com/pkgs/main/

specs:
  - python 3.7*
  - conda
  - https://repo.anaconda.com/pkgs/main/linux-64/pycurl-7.43.0.2-py37h1ba5d50_0.tar.bz2

```

And here is the error:

```
(base) brooksch@si-4377-linux:~/Downloads/constructor/siads505$ constructor .
platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Traceback (most recent call last):
  File "/home/brooksch/anaconda3/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/constructor/main.py", line 113, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/constructor/fcp.py", line 241, in main
    ignore_duplicate_files, verbose, dry_run
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/constructor/fcp.py", line 182, in _main
    precs = list(solver.solve_final_state())
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 274, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 554, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 520, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 541, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/home/brooksch/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 280, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - defaults/linux-64::pycurl==7.43.0.2=py37h1ba5d50_0
```

It looks like maybe there are other issues with this, but the instructions for moving forward are really unclear. Can one just retrieve all of the files stick them in a directory and get constructor to load those packages as well, instead of trying to parse out information from the lines of the spec file?

**Comment by mcg1969** [comment]
I'll mark this as an enhancement but I must be honest this is not going to be straightforward. Constructor's working assumption is that the list of specs can basically be passed to an equivalent `conda create` command. So if you try this:
```
conda create -n test conda python=3.7 https://repo.anaconda.com/pkgs/main/osx-64/pycurl-7.43.0.2-py37ha12b0ac_0.tar.bz2
```
you get this:
```
CondaValueError: cannot mix specifications with conda package filenames
```
Constructor is not likely to get ahead of conda here. The right way to do this, it seems, is to put these packages in a local, indexed channel.

**Comment by mcg1969** [comment]
And unfortunately #269 might get in the way of my proposed solution above.
