### ISSUE TITLE
Existing file causes error

### ISSUE THREAD

**Issue by lfloeer** [conda/constructor#29]
I have a constructor file like the following

```yaml
name: Rattlesnake
version: 1.0.0.0

channels:
  - https://repo.continuum.io/pkgs/r/
  - https://repo.continuum.io/pkgs/free/

specs:
  - python 3.5*
  - anaconda
  - r-essentials
```

Running constructor more than once results in the following error on a Windows 10 system:
```shell
platform: win-64
Fetching package metadata .....
Solving package specifications: ..........

fetching: https://repo.continuum.io/pkgs/r::m2w64-bwidget-1.9.10-1.tar.bz2
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 441, in download
    os.rename(pp, dst_path)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\<USERNAME>\\.conda\\constructor\\win-64\\m2w64-bwidget-1.9.10-1.tar.bz2.part' -> 'C:\\Users\\<USERNAME>\\.conda\\constructor\\win-64\\m2w64-bwidget-1.9.10-1.tar.bz2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\constructor-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\constructor\main.py", line 146, in main
    verbose=opts.verbose)
  File "C:\Anaconda3\lib\site-packages\constructor\main.py", line 81, in main_build
    fcp.main(info, verbose=verbose)
  File "C:\Anaconda3\lib\site-packages\constructor\fcp.py", line 185, in main
    fetch(info)
  File "C:\Anaconda3\lib\site-packages\constructor\fcp.py", line 162, in fetch
    fetch_pkg(pkginfo, download_dir)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 326, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 444, in download
    (pp, dst_path, e))
RuntimeError: Could not rename 'C:\\Users\\<USERNAME>\\.conda\\constructor\\win-64\\m2w64-bwidget-1.9.10-1.tar.bz2.part' to 'C:\\Users\\<USERNAME>\\.conda\\constructor\\win-64\\m2w64-bwidget-1.9.10-1.tar.bz2': FileExistsError(17, 'Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist')
```

The german parts in this message mean "A file cannot be created if it already exists". Deleting the `.conda/constructor` directory solves this issue but causes a lengthy re-download of all packages.

**Comment by lfloeer** [comment]
I've just re-run the constructor file with a fresh install of Anaconda3 4.1.0 (conda 4.1.6, constructor 1.2.1) and cannot re-create the issue. As for my other issue, this seems to be fixed now.
