### ISSUE TITLE
R-Channel causes wrong filenames in generated main.nsi

### ISSUE THREAD

**Issue by lfloeer** [conda/constructor#30]
I have the following constructor file:

```yaml
name: Rattlesnake
version: 1.0.0.0

channels:
  - https://repo.continuum.io/pkgs/r/
  - https://repo.continuum.io/pkgs/free/

specs:
  - python 3.5*
  - anaconda
  - r-essentials
```

Running constructor on a Windows 10 machine results in the following error message:
```bash
platform: win-64
Fetching package metadata .....
Solving package specifications: ..........

fetching: python-3.5.1-4.tar.bz2
<SNIP>
fetching: heapdict-1.0.0-py35_0.tar.bz2
fetching: https://repo.continuum.io/pkgs/r::m2w64-bwidget-1.9.10-1.tar.bz2
<SNIP>
fetching: https://repo.continuum.io/pkgs/r::r-zoo-1.7_13-r3.3.0_0.tar.bz2
fetching: idna-2.0-py35_0.tar.bz2
<SNIP>
fetching: zlib-1.2.8-vc14_2.tar.bz2
Reading: C:\Anaconda3\lib\site-packages\constructor\nsis\main.nsi.tmpl
MSVC runtimes found: ['vs2015_runtime-14.00.23026.0-0.tar.bz2']
Created C:\Users\<USERNAME>\AppData\Local\Temp\tmppnnabn7b\main.nsi file
Calling: ['C:\\Anaconda3\\NSIS\\makensis.exe', '/V2', 'C:\\Users\\<USERNAME>\\AppData\\Local\\Temp\\tmppnnabn7b\\main.nsi']
File: "C:\Users\<USERNAME>\.conda\constructor\win-64\https://repo.continuum.io/pkgs/r::m2w64-bwidget-1.9.10-1.tar.bz2" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "C:\Users\<USERNAME>\AppData\Local\Temp\tmppnnabn7b\main.nsi" on line 735 -- aborting creation process
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\constructor-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\constructor\main.py", line 146, in main
    verbose=opts.verbose)
  File "C:\Anaconda3\lib\site-packages\constructor\main.py", line 84, in main_build
    create(info)
  File "C:\Anaconda3\lib\site-packages\constructor\winexe.py", line 156, in create
    check_call(args)
  File "C:\Anaconda3\lib\subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Anaconda3\\NSIS\\makensis.exe', '/V2', 'C:\\Users\\<USERNAME>\\AppData\\Local\\Temp\\tmppnnabn7b\\main.nsi']' returned non-zero exit status 1
```

Opening the file `C:\Users\<USERNAME>\AppData\Local\Temp\tmppnnabn7b\main.nsi`, removing all instances of `https://repo.continuum.io/pkgs/r::` and running the last command manually creates a functioning installer.

Example entry in `main.nsi` before manual edit
```nsis
    # --> https://repo.continuum.io/pkgs/r::m2w64-bwidget-1.9.10-1.tar.bz2 <--
    File "C:\Users\<USERNAME>\.conda\constructor\win-64\https://repo.continuum.io/pkgs/r::m2w64-bwidget-1.9.10-1.tar.bz2"
    untgz::extract "-d" "$INSTDIR" "-zbz2" "$INSTDIR\pkgs\https://repo.continuum.io/pkgs/r::m2w64-bwidget-1.9.10-1.tar.bz2"
    ExecWait '"$INSTDIR\pythonw.exe" "$INSTDIR\Lib\_nsis.py" postpkg'
    Delete "$INSTDIR\pkgs\https://repo.continuum.io/pkgs/r::m2w64-bwidget-1.9.10-1.tar.bz2"
```

**Comment by ajoros** [comment]
Did you ever solve this issue? I am having problems too and i opened main.nsi but I dont have any instances of the urls similar to yours that you commented out.

**Comment by ilanschnell** [comment]
Which version of constructor and conda are you using?  Changes in conda 4.1.x broke constructor <1.2, but constructor 1.2.1 should be fixed to work with the latest conda again.

**Comment by mcg1969** [comment]
Should we adjust the dependencies for the new and older versions of `constructor` to insure that they are paired together properly?

**Comment by mingwandroid** [comment]
I've not yet looked at constructor, I think @mcg1969 and @ilanschnell are best placed to solve this one?

**Comment by lfloeer** [comment]
I've just re-run the constructor file with a fresh install of Anaconda3 4.1.0 (conda 4.1.6, constructor 1.2.1) and cannot re-create the issue. As far as i can tell, this seems to be fixed.

**Comment by mingwandroid** [comment]
Thanks for letting us know, I'll close this.
