### ISSUE TITLE
constructor 3 fails with 4.7.11 exe on Linux

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#301]
The 4.7.11 conda executable for Linux 64 seems to be incompatible with constructor 3. Trying it with the miniconda example (or several others I have tried) yield errors like this:
```
Welcome to MinicondaX X

MinicondaX will now be installed into this location:
/home/builder/minicondax

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/builder/minicondax] >>> /home/builder/test
PREFIX=/home/builder/test
Unpacking payload ...
read filter "zstd" is not supported
write filter "zstd" is not supported
  0%|                                                    | 0/35 [00:00<?, ?it/s]Process ForkProcess-1:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "concurrent/futures/process.py", line 233, in _process_worker
  File "multiprocessing/queues.py", line 113, in get
AttributeError: Can't get attribute '_extract' on <module '__main__' (built-in)>
Traceback (most recent call last):                                              
  File "conda.exe.py", line 79, in <module>
  File "concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 598, in result_iterator
  File "concurrent/futures/_base.py", line 435, in result
  File "concurrent/futures/_base.py", line 384, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[81680] Failed to execute script conda.exe
```
Here is the exact command line:
```
constructor --conda-exe conda-4.7.11-linux-64.exe .
```

**Comment by forrestwaters** [comment]
The 4.7.12 standalone should work which is what the latest link is pointed had: https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe. There were a few kinks we had to work out when going from 4.7.5 to 4.7.12 and the 4.7.11 ones had some issues. We should probably remove them as to not confuse anyone.
