### ISSUE TITLE
Can not create installer with only Python3.7 and jupyter on Windows

### ISSUE THREAD

**Issue by EisW** [conda/constructor#332]
Given the following minimal construct.yaml:

```yaml
name: my-anaconda
version: 0.0.1

install_in_dependency_order: True

channels:
  - http://repo.continuum.io/pkgs/main/

specs:
  - python 3.7*
  - jupyter
```

constructor failes resolving dependencies. Here the shown output:
```
(base) E:\git\sb-anaconda\sb-anaconda>constructor E:/git/sb-anaconda/sb-anaconda/construct/sb-anaconda3-py37-test
platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "E:\Miniconda3\Scripts\constructor-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\Miniconda3\lib\site-packages\constructor\main.py", line 242, in main
    dry_run=args.dry_run, conda_exe=args.conda_exe)
  File "E:\Miniconda3\lib\site-packages\constructor\main.py", line 118, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "E:\Miniconda3\lib\site-packages\constructor\fcp.py", line 244, in main
    ignore_duplicate_files, verbose, dry_run
  File "E:\Miniconda3\lib\site-packages\constructor\fcp.py", line 185, in _main
    precs = list(solver.solve_final_state())
  File "E:\Miniconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "E:\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "E:\Miniconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "E:\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "E:\Miniconda3\lib\site-packages\conda\resolve.py", line 1318, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "E:\Miniconda3\lib\site-packages\conda\resolve.py", line 351, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
jupyter -> ipywidgets -> python[version='>=3.5']
python=3.7
jupyter -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
```

Manual install of meta-package jupyter in e.g. Miniconda envrionment is o.k., only construct is not possible. Given Python 3.6* it works! On Linux there is no problem.

Here the used Miniconda3:
```
(base) E:\git\sb-anaconda\sb-anaconda>conda list
packages in environment at E:\Miniconda3:

Name                    Version                   Build  Channel
asn1crypto                1.2.0                    py37_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
beautifulsoup4            4.8.2                    py37_0
bzip2                     1.0.8                he774522_0
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py37_0
cffi                      1.13.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
conda                     4.8.2                    py37_0
conda-build               3.18.11                  py37_0
conda-package-handling    1.6.0            py37h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         3
constructor               3.0.0                    py37_0
cryptography              2.8              py37h7a1dbc1_0
filelock                  3.0.12                     py_0
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   py37_0
glob2                     0.7                        py_0
idna                      2.8                      py37_0
jinja2                    2.11.1                     py_0
jpeg                      9b                   hb83a4c4_2
libarchive                3.3.3                h0643e63_5
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_3
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.9                h464c3ec_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
markupsafe                1.1.1            py37he774522_0
menuinst                  1.4.16           py37he774522_0
nsis                      3.01                          8
olefile                   0.46                     py37_0
openssl                   1.1.1d               he774522_4
pillow                    7.0.0            py37hcc1f983_0
pip                       19.3.1                   py37_0
pkginfo                   1.5.0.1                  py37_0
powershell_shortcut       0.0.1                         2
psutil                    5.6.7            py37he774522_0
py-lief                   0.9.0            py37ha925a31_3
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pyopenssl                 19.0.0                   py37_0
pysocks                   1.7.1                    py37_0
python                    3.7.4                h5263a28_0
python-libarchive-c       2.8                     py37_13
pytz                      2019.3                     py_0
pywin32                   223              py37hfa6e2cd_1
pyyaml                    5.3              py37he774522_0
requests                  2.22.0                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
setuptools                41.4.0                   py37_0
six                       1.12.0                   py37_0
soupsieve                 1.9.5                    py37_0
sqlite                    3.30.0               he774522_0
tk                        8.6.8                hfa6e2cd_0
tqdm                      4.36.1                     py_0
urllib3                   1.24.2                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```

By the way: thank you for the great job in providing constructor and the whole conda environment, it saves me a lot of time !

**Comment by jjhelmus** [comment]
One Windows some of the dependencies of jupyter require packages from the `msys2` channel.  This channel must be included in the channel list.  

The following `construct.yaml` file will create the desired installer:

``` yaml
name: my-anaconda
version: 0.0.1

install_in_dependency_order: True

channels:
  - http://repo.anaconda.com/pkgs/main
  - http://repo.anaconda.com/pkgs/msys2

specs:
  - python 3.7*
  - jupyter
```
