### ISSUE TITLE
File not found when trying to create a pkg

### ISSUE THREAD

**Issue by marimeireles** [conda/constructor#379]
I'm having some really strange issues with constructor.
First, I had a lot of problems with dependencies, problems that don't necessarily make sense like this one:

```
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libcxxabi conflicts for:
python==3.7 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='1|4|0|3|2|hcfea43d_1']
r-rcpp -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='1|4|0|3|2|hcfea43d_1']
```

Then, I updated my `constructor.yaml` to have all the dependencies that my conda environment had: https://pastebin.com/w7J2aeQK

And now I'm encountering this new issue:

```
Traceback (most recent call last):
  File "/Users/mariana/Development/miniconda/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/main.py", line 244, in main
    dry_run=args.dry_run, conda_exe=args.conda_exe)
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/main.py", line 119, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/fcp.py", line 262, in main
    ignore_duplicate_files, verbose, dry_run
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/fcp.py", line 232, in _main
    pc_recs, platform, ignore_duplicate_files
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/fcp.py", line 142, in check_duplicates_files
    getsize(join(extracted_package_dir, short_path)))
  File "/Users/mariana/Development/miniconda/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mariana/.conda/constructor/osx-64/gsl-2.6-ha2d443c_0/lib/libgslcblas.0.dylib'
```

But if I `ls` to this directory the file is there.
Interestingly, if I run the command `construct .` again I'll get that another file is missing:

```
Traceback (most recent call last):
  File "/Users/mariana/Development/miniconda/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/main.py", line 244, in main
    dry_run=args.dry_run, conda_exe=args.conda_exe)
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/main.py", line 119, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/fcp.py", line 262, in main
    ignore_duplicate_files, verbose, dry_run
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/fcp.py", line 232, in _main
    pc_recs, platform, ignore_duplicate_files
  File "/Users/mariana/Development/miniconda/lib/python3.7/site-packages/constructor/fcp.py", line 142, in check_duplicates_files
    getsize(join(extracted_package_dir, short_path)))
  File "/Users/mariana/Development/miniconda/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mariana/.conda/constructor/osx-64/gfortran_osx-64-7.5.0-h81c6165_6/lib/gcc/x86_64-apple-darwin13.4.0/7.5.0/clang'
```

But again, if I `ls` to this dir, it is there.
I'm running these tests on a osx 10.15.6, my colleague tried in a fedora 30.

Any idea of what might be happening here?
Thanks a lot.

**Comment by marimeireles** [comment]
Apparently this issue was fixed in master, we just need a new release.
I think you can close this if you want.
Thanks!
