### ISSUE TITLE
environment and environment_file modes broken

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#400]
Given the following `construct.yaml` file:
```
name: envinstall
version: X
installer_type: all
environment: envtest
channels:
  - defaults
```
Create a simple environment called `envtest` (e.g., `conda create -n envtest python conda`), and run the master build of constructor. The following error occurs:
```
platform: osx-64
Traceback (most recent call last):
  File "/Users/mgrant/miniconda3/bin/constructor", line 11, in <module>
    load_entry_point('constructor', 'console_scripts', 'constructor')()
  File "/Users/mgrant/Repos/constructor/constructor/main.py", line 245, in main
    dry_run=args.dry_run, conda_exe=conda_exe)
  File "/Users/mgrant/Repos/constructor/constructor/main.py", line 111, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run, conda_exe=conda_exe)
  File "/Users/mgrant/Repos/constructor/constructor/fcp.py", line 349, in main
    verbose, dry_run, conda_exe,
  File "/Users/mgrant/Repos/constructor/constructor/fcp.py", line 277, in _main
    precs = _precs_from_environment(environment, download_dir, user_conda)
UnboundLocalError: local variable 'user_conda' referenced before assignment
```
[This commit](https://github.com/conda/constructor/commit/fb70afb4ce9eafe08e4279ba8a3019365831c320) is the case of this error.

But then let's do `conda env export > envtest.yml` and modify the above `construct.yaml` as follows:
```
name: envinstall
version: X
installer_type: all
environment_file: envtest.yml
channels:
  - defaults
```
This bypasses the above error, and now produces this one:
```
Traceback (most recent call last):
  File "/Users/mgrant/miniconda3/bin/constructor", line 11, in <module>
    load_entry_point('constructor', 'console_scripts', 'constructor')()
  File "/Users/mgrant/Repos/constructor/constructor/main.py", line 245, in main
    dry_run=args.dry_run, conda_exe=conda_exe)
  File "/Users/mgrant/Repos/constructor/constructor/main.py", line 111, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run, conda_exe=conda_exe)
  File "/Users/mgrant/Repos/constructor/constructor/fcp.py", line 349, in main
    verbose, dry_run, conda_exe,
  File "/Users/mgrant/Repos/constructor/constructor/fcp.py", line 277, in _main
    precs = _precs_from_environment(environment, download_dir, user_conda)
  File "/Users/mgrant/Repos/constructor/constructor/fcp.py", line 235, in _precs_from_environment
    **package))
  File "/Users/mgrant/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/entity.py", line 722, in __call__
    instance = super(EntityType, cls).__call__(*args, **kwargs)
  File "/Users/mgrant/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/entity.py", line 739, in __init__
    setattr(self, key, kwargs[key])
  File "/Users/mgrant/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/entity.py", line 430, in __set__
    instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
  File "/Users/mgrant/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/entity.py", line 569, in box
    raise ValidationError(val, msg=e1)
conda._vendor.auxlib.exceptions.ValidationError: 'osx-64' is not a valid Platform
````
The cause here is the that the `**package` kwargs include a `platform` value of `osx-64`, but in fact, in conda, that should be `subdir`, not `platform`.

I have to confess, I don't understand why this ever worked.

**Comment by mcg1969** [comment]
@isuruf can you take a look at this?

**Comment by isuruf** [comment]
I don't understand how this worked either. Fixed in https://github.com/conda/constructor/pull/401 anyway along with the breakage created by https://github.com/conda/constructor/commit/fb70afb4ce9eafe08e4279ba8a3019365831c320

**Comment by mcg1969** [comment]
Thank you!
