### ISSUE TITLE
Cannot access the listed channels in construct.yaml

### ISSUE THREAD

**Issue by hans-permana** [conda/constructor#50]
Hi all,

We have used this library to build an installer for DeDop project (https://github.com/DeDop/dedop-conda) and it works fine when it refers to a local package. However, now is the time to upload the package to Anaconda cloud and we did (https://anaconda.org/pans/dedop). This link is placed under channels in the yaml file. Unfortunately, it always returns with the following error:
```
> constructor installer                                                                                                      
platform: win-64                                                                                                             
Fetching package metadata: ...Traceback (most recent call last):                                                             
  File "C:\Miniconda3\lib\site-packages\libconda\fetch.py", line 98, in fetch_repodata                                       
    resp.raise_for_status()                                                                                                  
  File "C:\Miniconda3\lib\site-packages\requests\models.py", line 884, in raise_for_status                                   
    raise HTTPError(http_error_msg, response=self)                                                                           
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://anaconda.org/pans/dedop/win-64/repodata.json.bz2 
                                                                                                                             
During handling of the above exception, another exception occurred:                                                          
                                                                                                                             
Traceback (most recent call last):                                                                                           
  File "C:\Miniconda3\Scripts\constructor-script.py", line 5, in <module>                                                    
    sys.exit(constructor.main.main())                                                                                        
  File "C:\Miniconda3\lib\site-packages\constructor\main.py", line 149, in main                                              
    verbose=opts.verbose)                                                                                                    
  File "C:\Miniconda3\lib\site-packages\constructor\main.py", line 84, in main_build                                         
    fcp.main(info, verbose=verbose)                                                                                          
  File "C:\Miniconda3\lib\site-packages\constructor\fcp.py", line 179, in main                                               
    for url in info['channels']                                                                                              
  File "C:\Miniconda3\lib\site-packages\libconda\utils.py", line 68, in __call__                                             
    value = self.func(*args, **kw)                                                                                           
  File "C:\Miniconda3\lib\site-packages\libconda\fetch.py", line 218, in fetch_index                                         
    repodatas.append((url, future.result()))                                                                                 
  File "C:\Miniconda3\lib\concurrent\futures\_base.py", line 398, in result                                                  
    return self.__get_result()                                                                                               
  File "C:\Miniconda3\lib\concurrent\futures\_base.py", line 357, in __get_result                                            
    raise self._exception                                                                                                    
  File "C:\Miniconda3\lib\concurrent\futures\thread.py", line 55, in run                                                     
    result = self.fn(*self.args, **self.kwargs)                                                                              
  File "C:\Miniconda3\lib\site-packages\libconda\fetch.py", line 62, in func                                                 
    res = f(*args, **kwargs)                                                                                                 
  File "C:\Miniconda3\lib\site-packages\libconda\fetch.py", line 141, in fetch_repodata                                      
    raise RuntimeError(msg)                                                                                                  
RuntimeError: Could not find URL: https://anaconda.org/pans/dedop/win-64/                                                    
```

It seems that it tries to find this file repodata.json.bz2, which is simply not there. Why is it looking for this file? I have had a look at other Anaconda packages and only a small number of them are browseable with /win-64 (or osx-64 etc.). Can you give me an enlightenment? 

Here are some information about my environment:
**conda-env** : 2.6.0
**conda-build** : 2.0.10
**constructor** : 1.5.0
**conda** : 4.2.13
**python** : 3.5.2.final.0
**platform** : win-64

Thank you,

Hans

**Comment by ilanschnell** [comment]
It seems like the channel URL invalid.  It URL should start with `https://conda.anaconda.org/`.

**Comment by hans-permana** [comment]
You are right @ilanschnell ! Changed the URL to https://conda.anaconda.org/pans and it works fine. Thanks.

**Comment by ilanschnell** [comment]
I'm happy I was able to help.
