### ISSUE TITLE
Adding a license file makes NSIS fail (windows)

### ISSUE THREAD

**Issue by NicoKiaru** [conda/constructor#657]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have a yaml file which runs just fine and creates and installer on Windows. However the license is still the placeholder license.

So I created a LICENSE.txt file and added in the yaml file the line:
```
license_file: LICENSE.txt
```

Now, running `constructor .` gives me this error message:

```
Checking for 'C:\Users\nicol\.conda\envs\constructor-12-03-23\NSIS\makensis.exe'
INFO:constructor.winexe:NSIS version: v3.08
INFO:constructor.winexe:Reading: C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\site-packages\constructor\nsis\main.nsi.tmpl
INFO:constructor.winexe:Created C:\Users\nicol\AppData\Local\Temp\tmpjlmir5xs\main.nsi file
INFO:constructor.winexe:Calling: ['C:\\Users\\nicol\\.conda\\envs\\constructor-12-03-23\\NSIS\\makensis.exe', '/V2', 'C:\\Users\\nicol\\AppData\\Local\\Temp\\tmpjlmir5xs\\main.nsi']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Scripts\constructor.exe\__main__.py", line 7, in <module>
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\site-packages\constructor\main.py", line 351, in main
    main_build(dir_path, output_dir=out_dir, platform=args.platform,
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\site-packages\constructor\main.py", line 175, in main_build
    create(info, verbose=verbose)
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\site-packages\constructor\winexe.py", line 420, in create
    process.check_returncode()
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\subprocess.py", line 501, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['C:\\Users\\nicol\\.conda\\envs\\constructor-12-03-23\\NSIS\\makensis.exe', '/V2', 'C:\\Users\\nicol\\AppData\\Local\\Temp\\tmpjlmir5xs\\main.nsi']' returned non-zero exit status 1.
```

And no installer is created. It's not a super problematic bug: people can live with the placeholder license file. But it would be nice to know what's wrong and fix it.

I use conda constructor on windows 10, NSIS 3.08, and pulled conda-constructor from source (I guess) on the 12th March 2023 (as explained in https://github.com/conda/constructor/issues/580#issuecomment-1377560305)

-----------------------

### Conda Info

```shell
active environment : base
    active env location : C:\Users\nicol\.conda\envs\constructor-12-03-23
            shell level : 2
       user config file : C:\Users\nicol\.condarc
 populated config files : C:\Users\nicol\.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.11.0.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.0=0
                          __win=0=0
       base environment : C:\Users\nicol\.conda\envs\constructor-12-03-23  (writable)
      conda av data dir : C:\Users\nicol\.conda\envs\constructor-12-03-23\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\nicol\.conda\envs\constructor-12-03-23\pkgs
                          C:\Users\nicol\.conda\pkgs
                          C:\Users\nicol\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\nicol\.conda\envs\constructor-12-03-23\envs
                          C:\Users\nicol\.conda\envs
                          C:\Users\nicol\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.11.0 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\nicol\.condarc <==
ssl_verify: True
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
# packages in environment at C:\Users\nicol\.conda\envs\constructor-12-03-23:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py311ha68e1ae_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h7d9ee11_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.11.1         py311h1ea47a8_1    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
conda-standalone          22.11.1              h57928b3_0    conda-forge
constructor               0+unknown                pypi_0    pypi
cryptography              39.0.2          py311h28e9c30_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libdeflate                1.17                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libtiff                   4.5.0                hc3b8658_5    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
menuinst                  1.4.19          py311h1ea47a8_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nsis                      3.08                 h2be35fd_1    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.0.8                hcfcfb64_0    conda-forge
pillow                    9.4.0           py311hc67b2de_2    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pycosat                   0.6.4           py311ha68e1ae_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.11.0          hcf16a7b_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py311ha68e1ae_3    conda-forge
ruamel.yaml.clib          0.2.7           py311ha68e1ae_1    conda-forge
ruamel_yaml               0.15.80         py311ha68e1ae_1008    conda-forge
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zstandard                 0.19.0          py311he5d195f_1    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```

**Comment by jaimergp** [comment]
We do use licenses in several examples (e.g. [the `miniforge` one](https://github.com/conda/constructor/blob/fd792dea6080ecee38869866a8e38e8eaaed300d/examples/miniforge/construct.yaml#L4)), so this is definitely supported.

Is there a chance you can share your license file? Maybe there's a weird encoding issue NSIS is choking on. Maybe you can run `constructor` in verbose mode to get more details?

**Comment by NicoKiaru** [comment]
Sure it is this one:

https://github.com/NicoKiaru/ABBA-Python/blob/dev/constructor/LICENCE.txt

I did not know there was a verbose mode. I'll check that, thanks!

**Comment by jaimergp** [comment]
Let's give it a try without the [copyright symbol in this line](https://github.com/NicoKiaru/ABBA-Python/blob/8b1f6de2be7a408aac3be7f6a7d5922cc7eae283/constructor/LICENCE.txt#L10). Replace it with `(C)` for now and see if it works.

**Comment by NicoKiaru** [comment]
Hum, no luck so far. But ok, if you think  that's a symbol issue, there are a few other things to check. '<>' and a few ` and ' characters. 

How can I run in verbose ? Simply `constructor -v .` ?

**Comment by NicoKiaru** [comment]
Running with -v gives this output:

```
NFO:constructor.winexe:Created C:\Users\nicol\AppData\Local\Temp\tmp5xhni99w\main.nsi file
INFO:constructor.winexe:Calling: ['C:\\Users\\nicol\\.conda\\envs\\constructor-12-03-23\\NSIS\\makensis.exe', '/V4', 'C:\\Users\\nicol\\AppData\\Local\\Temp\\tmp5xhni99w\\main.nsi']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Scripts\constructor.exe\__main__.py", line 7, in <module>
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\site-packages\constructor\main.py", line 351, in main
    main_build(dir_path, output_dir=out_dir, platform=args.platform,
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\site-packages\constructor\main.py", line 175, in main_build
    create(info, verbose=verbose)
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\site-packages\constructor\winexe.py", line 420, in create
    process.check_returncode()
  File "C:\Users\nicol\.conda\envs\constructor-12-03-23\Lib\subprocess.py", line 501, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['C:\\Users\\nicol\\.conda\\envs\\constructor-12-03-23\\NSIS\\makensis.exe', '/V4', 'C:\\Users\\nicol\\AppData\\Local\\Temp\\tmp5xhni99w\\main.nsi']' returned non-zero exit status 1.
```

I could try to make a very small installer and debug the license file. I'll try to  find the time and will report here.

**Comment by jaimergp** [comment]
Hm, we should have seen the stdout and stderr from makensis thanks to these lines:

```
    logger.debug("makensis stdout:\n'%s'", process.stdout)
    logger.debug("makensis stderr:\n'%s'", process.stderr)
```

Can you pass the `--debug` flag too?
