### ISSUE TITLE
windows failing at begininning (1.5.5)

### ISSUE THREAD

**Issue by looooo** [conda/constructor#78]
```
(C:\Users\fc_builder\Miniconda3) C:\Users\fc_builder\projects\constructor\examples>constructor maxic
onda
platform: win-64
Fetching package metadata: Traceback (most recent call last):
  File "C:\Users\fc_builder\Miniconda3\Scripts\constructor-script.py", line 5, in <module>
    sys.exit(constructor.main.main())
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\constructor\main.py", line 177, in main
    verbose=opts.verbose, cache_dir=opts.cache_dir)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\constructor\main.py", line 87, in main_buil
d
    fcp.main(info, verbose=verbose)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\constructor\fcp.py", line 180, in main
    for url in info['channels']
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\libconda\utils.py", line 68, in __call__
    value = self.func(*args, **kw)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\libconda\fetch.py", line 218, in fetch_inde
x
    repodatas.append((url, future.result()))
  File "C:\Users\fc_builder\Miniconda3\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Users\fc_builder\Miniconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\fc_builder\Miniconda3\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\libconda\fetch.py", line 62, in func
    res = f(*args, **kwargs)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\libconda\fetch.py", line 97, in fetch_repod
ata
    headers=headers, proxies=session.proxies)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\sessions.py", line 488, in request

    resp = self.send(prep, **send_kwargs)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\sessions.py", line 630, in <listco
mp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\sessions.py", line 190, in resolve
_redirects
    **adapter_kwargs
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py
", line 594, in urlopen
    chunked=chunked)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py
", line 350, in _make_request
    self._validate_conn(conn)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py
", line 835, in _validate_conn
    conn.connect()
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\packages\urllib3\connection.py", l
ine 323, in connect
    ssl_context=context)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", li
ne 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl
.py", line 392, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\OpenSSL\SSL.py", line 525, in load_verify_l
ocations
    _raise_current_error()
  File "C:\Users\fc_builder\Miniconda3\lib\site-packages\OpenSSL\_util.py", line 48, in exception_fr
om_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_
new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

**Comment by looooo** [comment]
will test with current master...
